apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-istio-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "80"
spec:
  selector:
    istio: ingressgateway
  servers:
  - port: { number: 80, name: http, protocol: HTTP }
    hosts: [ "*" ]
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-app-dr
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Release.Name }}-django-app-service
  subsets:
  - name: v1
    labels: { version: v1 }
  - name: v2
    labels: { version: v2 }
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-entry-service
  namespace: {{ .Release.Namespace }}
spec:
  gateways: [ {{ .Release.Name }}-istio-gateway ]
  hosts: [ "*" ]
  http:
  - match:
    - uri:
        prefix: /
    route:
    {{- with .Values.istio.routes }}
    {{- range . }}
    - destination:
        host: {{ $.Release.Name }}-django-app-service
        subset: {{ .version }}
      weight: {{ .weight }}
    {{- end }}
    {{- end }}