global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app:8000']

  - job_name: 'model_service'
    static_configs:
      - targets: ['model_service:5000']
